version: '3.4'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: 'jlabs'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - '3306:3306'

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      - "9080:9080"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  eurekaserver:
    hostname: eurekaserver
    build:
      context: eurekaserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - mysql

  configserver:
    hostname: configserver
    environment:
      - WAITFORIT_HOST=eurekaserver
      - WAITFORIT_PORT=8761
      - WAITFORIT_TIMEOUT=120
      - EUREKA_SERVER=http://eurekaserver:8761/eureka
    build:
      context: configserver
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eurekaserver

  apigateway:
    hostname: apigateway
    environment:
      - EUREKA_SERVER=http://eurekaserver:8761/eureka
      - CONFIG_SERVER=http://configserver:8888
      - RABBIT=rabbit
      - WAITFORIT_HOST=configserver
      - WAITFORIT_PORT=8888
      - WAITFORIT_TIMEOUT=250
    build:
      context: apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - configserver

  phone-app:
    hostname: phone-app
    environment:
      - EUREKA_SERVER=http://eurekaserver:8761/eureka
      - CONFIG_SERVER=http://configserver:8888
      - MYSQL=mysql:3306
      - RABBIT=rabbit
      - PORT=8082
      - WAITFORIT_HOST=configserver
      - WAITFORIT_PORT=8888
      - WAITFORIT_TIMEOUT=250
    build:
      context: eurekaclient
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - apigateway

  phone-app2:
    hostname: phone-app
    environment:
      - EUREKA_SERVER=http://eurekaserver:8761/eureka
      - CONFIG_SERVER=http://configserver:8888
      - MYSQL=mysql:3306
      - RABBIT=rabbit
      - PORT=8081
      - WAITFORIT_HOST=configserver
      - WAITFORIT_PORT=8888
      - WAITFORIT_TIMEOUT=250
    build:
      context: eurekaclient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - apigateway